### PR TITLE
fix(front): reshape bbox with positive height/width

### LINKED ISSUE #118: bbox label misplaced when bbox created from right to left
If you drag from right to left, the label is positionned on the top right:
image

We should reorder bbox coordinates at creation, as bbox can be created with negative width/height

### PR DESCRIPTION
**Pull request by BertrandRenault**
close #118

### CODE REVIEW

File: ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte [hunk 1]
```diff
@@ -53,10 +53,12 @@
           ...baseObject,
           bbox: {
             coords: [
-              shape.attrs.x / shape.imageWidth,
-              shape.attrs.y / shape.imageHeight,
-              shape.attrs.width / shape.imageWidth,
-              shape.attrs.height / shape.imageHeight,
+              (shape.attrs.width < 0 ? shape.attrs.x + shape.attrs.width : shape.attrs.x) /
```
Comment (timothee-LJN) [inline ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte:56]: to make code easier to read, you could keep values in variables : 
```
 const x = rect.x();
 const y = rect.y();
 const width = rect.width();
const height = rect.height();
newShape = {
status: "inProgress",
attrs: {
  x: width < 0 ? x + width : x,
  y: height < 0 ? y + height : y,
  width: Math.abs(width) / shape.imageWidth,
  height: Math.abs(height) / shape.imageHeight,
 },
};

```

**Review by timothee-LJN — APPROVED** [review]
To avoid getting the same problem when resizing rectangle, you could update `resizeStroke` in `Rectangle.svelte`  as follow: 
```
  const onTransform = () => {
    if (currentRect.getAttr("rotation") < 0) {
      currentRect.setAttrs({
        rotation: 0,
      });
    }
    currentRect.setAttrs({
      width: currentRect.width() * currentRect.scaleX(),
      height: currentRect.height() * currentRect.scaleY(),
      scaleX: 1,
      scaleY: 1,
    });
    const tooltip: Konva.Label = stage.findOne(`#tooltip${bbox.id}`);
    stickLabelsToRectangle(tooltip, currentRect);
  };
```

**Comment by BertrandRenault** [comment]
used getClientRect({relativeTo: ...}) for better handling of rotated rect (resize out of object bounds does rotate 180 or -180)

**Review by cpvannier — APPROVED** [review]

**Review by timothee-LJN — APPROVED** [review]
