### PR TITLE
fix(front): Improve how stats are displayed in the app

### LINKED ISSUE #170: Improve how stats are displayed in the app
Stats are currently displayed in very small histograms, making them hard to read. Need to improve appearance and readability

### PR DESCRIPTION
**Pull request by ulysse-bonneau**
## Issue

Fixes #170 

## Description

* Improved appearance and readability of histograms :
image
* Changed library from Vega-lite to Chart.js
* Added a zoom feature 
* Responsiveness improved

### CODE REVIEW

File: ui/components/core/src/components/Histogram.svelte [hunk 1]
```diff
@@ -15,105 +15,81 @@
...
+  // Define props
   export let hist: DatasetStat;
-  export let maxHeight = 48;
-  export let hideTitle = false;
 
-  // Calculate histogram height
-  let h = 7.5 * hist.histogram.length;
-  h = h < 125 ? 125 : h;
+  // Color palette for stacked charts
+  const colors = ["#771E5F", "#1E7736", "#1E5F77", "#77361E"];
```
Comment (timothee-LJN) [inline ui/components/core/src/components/Histogram.svelte:36]: suggestion: it could be useful to keep those values in a setting file to re-use them later

File: ui/components/core/src/components/Histogram.svelte [hunk 2]
```diff
@@ -15,105 +15,81 @@
...
-    params: [
-      {
-        name: "highlight",
-        select: {
-          type: "point",
-          on: "mouseover",
-        },
+  // Separate splits
+  let splits: string[] = [...new Set(hist.histogram.map((item) => String(item.split)))];
+  let datasets: ChartDataset[] = [];
```
Comment (timothee-LJN) [inline ui/components/core/src/components/Histogram.svelte:40]: for consistency, I think its easier to read if variable are named after / consistent with their type
```
let chartDatasets: ChartDataset[] = []
```

File: ui/components/core/src/components/Histogram.svelte [hunk 3]
```diff
@@ -15,105 +15,81 @@
...
+  for (let i = 0; i < splits.length; ++i) {
```
Comment (timothee-LJN) [inline ui/components/core/src/components/Histogram.svelte:41]: suggestion : 
I tend to prefer map over for loop as it is more functional : https://medium.com/@ExplosionPills/map-vs-for-loop-2b4ce659fb03

```
datasets = splits.map(split, i => ({
labels: split,
 backgroundColor: colors[i] + "40",
...
})

File: ui/components/core/src/components/Histogram.svelte [hunk 4]
```diff
@@ -15,105 +15,81 @@
...
+
+  // Define label names
+  let labels;
+  if (hist.type == "numerical")
+    labels = [...new Set(hist.histogram.map((item) => item.bin_start + "-" + item.bin_end))];
+  else if (hist.type == "categorical")
+    labels = [...new Set(hist.histogram.map((item) => item[hist.name]))];
+
+  // Prepare chart data and options
+  let data = {
```
Comment (timothee-LJN) [inline ui/components/core/src/components/Histogram.svelte:59]: you can use ES6 shorthand:  https://ui.dev/shorthand-properties
let data = {
labels, 
datasets
}

File: ui/components/core/src/components/Histogram.svelte [hunk 5]
```diff
@@ -15,105 +15,81 @@
...
-
-  // Vega-lite chart options
-  const options = {
-    actions: false,
-  };
+  Chart.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, zoomPlugin);
 </script>
 
 <!-- Histogram -->
-<div class="max-h-{maxHeight} w-72 mx-auto flex flex-col justify-center items-center">
```
Comment (timothee-LJN) [inline ui/components/core/src/components/Histogram.svelte:110]: `max-h-{maxHeight}` won't work here because of how tailwind parses values https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

if you really need dynamic values, you can use css variables instead:
```
  <div
    class="..."
    style="max-height:{maxHeight}"
  >
```

**Review by timothee-LJN — APPROVED** [review]
following conventionnal commit, your PR should be name 
"fix(front): Improve ..." 

https://www.conventionalcommits.org/en/v1.0.0/#summary

File: ui/components/core/src/components/Histogram.svelte (hunk 5 above)
Comment (ulysse-bonneau) [reply ui/components/core/src/components/Histogram.svelte:110]: This line was deleted and dynamic values are no longer needed.

**Review by cpvannier — APPROVED** [review]

File: ui/components/core/src/components/Histogram.svelte (hunk 5 above)
Comment (timothee-LJN) [reply ui/components/core/src/components/Histogram.svelte:110]: yep i read too quickly!
