### PR TITLE
fix: S3 and URL wrongly handled

### LINKED ISSUE #95: Fix S3 support
Regressions:
- an environment variable required by lancedb for S3 (AWS_ENDPOINT renamed ENDPOINT_URL)
- URL images doesn't work anymore

### PR DESCRIPTION
**Pull request by BertrandRenault**
Fixes #95

- AWS_ENDPOINT and AWS_REGION are required by lancedb for S3, AWS_ENDPOINT was previously renamed to ENDPOINT_URL.
- URL images were not correctly handled

### CODE REVIEW

**Review by cpvannier — APPROVED** [review]

File: ui/components/core/src/utils.ts [hunk 1]
```diff
@@ -21,3 +21,11 @@ import { schemeSet3 } from "d3-scale-chromatic";
 export function ordinalColorScale(range: Iterable<string>) {
   return scaleOrdinal(schemeSet3).domain(range);
 }
+
```
Comment (timothee-LJN) [inline ui/components/core/src/utils.ts:24]: in order to better organize utils, there is a dedicated folder `core/src/lib/utils`. Maybe we could create an index file which would allow to do a `utils.fooFunction`?

File: ui/components/canvas2d/src/Canvas2D.svelte [hunk 2]
```diff
@@ -204,7 +204,11 @@
     for (const view of Object.values(selectedItem.views)) {
       zoomFactor[view.id] = 1;
       images[view.id] = new Image();
-      images[view.id].src = `/${view.uri}` || view.url;
+      if (utils.isValidURL(view.uri)) {
+        images[view.id].src = `${view.uri}` || view.url;
```
Comment (timothee-LJN) [inline ui/components/canvas2d/src/Canvas2D.svelte:208]: I think `|| view.url` was added here during data migration to avoid bugs but should probably not be needed in the future?

**Review by timothee-LJN — APPROVED** [review]

File: ui/components/canvas2d/src/Canvas2D.svelte (hunk 2 above)
Comment (BertrandRenault) [reply ui/components/canvas2d/src/Canvas2D.svelte:208]: agreed, but in a future PR
